### ISSUE TITLE
Manjaro Plasma Pinephone Pro (incompatibile/ not working.) (closed due to lack of fix/other.)

### ISSUE THREAD

**Issue by MadameMalady** [Raezroth/Linux-ARM-Gaming-Chroot#8]

**Comment by Raezroth** [comment]
Was the path you entered an absolute path? 

Also, the installer script should create a Steam shortcut to launch from phosh & plasma mobile's app drawer.

**Comment by MadameMalady** [comment]
The entered path was:
' /home/gaming_chroot '

**Comment by MadameMalady** [comment]
I went through and did additional testing, and tried installing it to the directory suggested, and I still got errors, the terminal started freezing a little, but here is a screenshot of the very first error message that pops up: ![image](https://user-images.githubusercontent.com/41642242/182962073-26bae46d-38ca-4113-a427-759efbcdfea3.jpeg)

**Comment by Raezroth** [comment]
That locale error is expected and can be ignored. We end up manual setting LC_ALL and LC_LANGUAGE in /root/.bashrc

There will be few things that will show errors due running in chroot but can be ignored. The setup process can also have wait time. Freezing can occur depending on host distro from what i found, but it is best to be patient.

**Comment by MadameMalady** [comment]
So I'll take it I should proceed to run the last few commands as prompted, and continue, and that the icons are added after first time initialization?

**Comment by MadameMalady** [comment]
I attempted to follow the rest of the instructions in the terminal, but they did not work. Running the command gaming_chroot_terminal in the terminal simply said it wasn't a known bash command, I'd be curious to see other users results, but at least on Manjaro Plasma on the Pro, I do not think this script is currently compatible with it.

**Comment by CalcProgrammer1** [comment]
I had a similar experience installing it in Danctnix Arch.  I ran the script, targeted /chroot/gaming as the chroot path.  It created the chroot just fine, but it did not install the gaming_chroot_terminal command or create a desktop file or anything.  When I manually chroot in, `su user` doesn't work, nor does `su user1` even though /home/user1 exists.

**Comment by Raezroth** [comment]
I have done a few commits to try to fix the user creation bug and the shortcut creation bug. If you can try creating the chroot again with the new edits and let me know. That would be great.

**Comment by MadameMalady** [comment]
![image](https://user-images.githubusercontent.com/41642242/183235387-52caf97a-c4d8-4bbb-affd-127abdfc2081.jpeg)
Went much faster, but still encountered errors with permissions.

**Comment by Raezroth** [comment]
remove " /opt/steam " " /bin/gaming_chroot_terminal" "/bin/steam-box" and  try running the installer as root?? it should have prompt you to run it with sudo or doas though.

**Comment by Raezroth** [comment]
also make sure you run the installer from inside the git clone path.

**Comment by MadameMalady** [comment]
So, in my last test, I did sudo rm -rf (git clone path)
sudo rm -rf 'd all the directories you mentioned, 
And git cloned again, cd'd to script path, and ran the script with sudo, commands still did not install 😔

**Comment by CalcProgrammer1** [comment]
Just tried again on Arch, same thing.  I did a git pull on master to make sure I was up to date, ran the script from

/home/adam/Linux-ARM-Gaming-Chroot/

Set chroot path to

/chroot/gaming

I had the failures writing steam-box and the gaming chroot script and those commands are not available.

Also, why /bin?  Why not /usr/local/bin?

Are you supposed to run the script itself as root?

**Comment by Raezroth** [comment]
The script should automatically ask for sudo or doas password so that wasn't it. I just move the scripts to a bin folder in the user's home directory and added that to path to fix permission issues

**Comment by Raezroth** [comment]
I also fixed in the script where they get created to and the uninstall option now deletes the shortcuts as well

**Comment by CalcProgrammer1** [comment]
I created a scripts folder in the chroot target (/chroot/gaming) and ran the script as root and it worked.  If the scripts directory doesn't exist it fails.

**Comment by Raezroth** [comment]
The latest commit should have a few fixes for that and some other things. even adding user1 to sudo group

**Comment by MadameMalady** [comment]
Did another battery of tests with the last changes, no difference yet that I can see. I also made a scripts directory in the chroot target directory as suggested by Adam and reran and it still doesn't seem to do anything (I am using the example directory for the chroot and typing it exactly as shown there)

Issues on lines 99 (no such directories)
Line 144 ( no such directories)
Line 168 (no such directories)

Nothing is being created or copied for directories and files as far as I can see.

**Comment by Raezroth** [comment]
Try cloning the installer script again. I updated to create a bin directory in the user's home folder and link it in path.

**Comment by Raezroth** [comment]
I had to clone the repo again to actually get the changes to the script for some reason

**Comment by MadameMalady** [comment]
I'm not sure if I'm just doing something wrong, or what, but it's still not working for me x.x

**Comment by MadameMalady** [comment]
So, I'm just going to put a few suggestions and close this, because the changes being made are not so far producing any noticeable changes on my end (when they are apparently doing things on at least Adams end) 
Suggestion one is to not make everything in the script so very variable based, it makes reading it a bit of a pain, the second would be additional code labeling. I'd also examine the lines for creating and copying directories, as they aren't working on Manjaro Plasma at all. And the last suggestion is to take all the extra steps the terminal lists for you, and just incorporate them into the installer as well. 

I will at some point whip together a version of this installer with what I think is a more readable menu style, and see if that helps solve the Manjaro Plasma issues.

**Comment by Raezroth** [comment]
I have went through and worked out all the bugs I can currently. The variables are there to help the installer and with out them, the installer would break itself.

**Comment by MadameMalady** [comment]
Yeah, I'm aware.
Would you be interested in a modified version of this installer, reworked with the kind of menu in describing? I think I can help work out some more bugs if I spend a couple days on it. (Take a look at my repository Manjaro Waydroid Manager if you'd like an idea of how I typically implement menus, just a fair warning it's about 544 lines ^^"..)
